### ISSUE TITLE
Add lumino to automerge_perf benchmarks

### ISSUE THREAD

**Issue by mweidner037** [composablesys/collabs#152]
https://github.com/jupyterlab/lumino/blob/8726968af142e44ca61ba28ab5f9f6911f34ee3f/datastore-benchmarks/results.md
More links in https://blog.jupyter.org/how-we-made-jupyter-notebooks-collaborative-with-yjs-b8dff6a9d8af

(Lumino is from Jupyter's home-brew CRDT library, before Yjs took over.)

**Comment by echarles** [comment]
Lumino datastore (CRDT implementation) is no more maintained and will prolly be officially depreacted at some point.

This issue can safely be close IMHO.
