### ISSUE TITLE
Approach for undo/redo?

### ISSUE THREAD

**Issue by echarles** [composablesys/collabs#208]
I wonder what is the intake of `collabs` for undo/redo.

Looking at the code and doc, I don't see any specific method to invoke undo/redo on the CRDT model.

If you type `CTRL-Z` while editing eg. https://compoventuals-tests.herokuapp.com/host.html?network=ws&container=demos/rich-text/dist/rich_text.html, I guess the Quill editor undo feature plays his role, and the change is propagated to the other participants, but this is not the undo/redo on the CRDT level as you would expect. In this case, we are more changes, instead of going back in the history of the CRDT.

**Comment by mweidner037** [comment]
We haven't seriously thought about this yet. There are some papers about undoing ops in CRDTs (https://crdt.tech/papers.html , check "Undoing operations"), but I think all you really need is the same thing as in a single-user app: each time the local user performs an op, you compute a semantic inverse of that op and push it onto an undo stack.

For CRDTs, the tricky part is that you need to ensure that your inverse ops still make sense in the face of operations from other users. E.g., the inverse of a text editing operation needs to reference the *immutable location* of its edit (which moves around as text is typed in front of it), not the literal index. That doesn't sound too difficult to me for our primitive CRDTs (e.g., `CText`), but we may run into issues when adding inverse ops to more complicated CRDTs.

**Comment by mweidner037** [comment]
https://github.com/composablesys/collabs/pull/247 adds a page to the Guide with advice on how to do basic, local undo/redo, like what Quill and Prosemirror do. I don't currently plan to add more direct support to the Collabs themselves.
